# Generated by Django 6.0.2 on 2026-03-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_pricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['height']},
        ),
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.IntegerField(db_index=True),
        ),
    ]
