# Generated by Django 6.0.2 on 2026-03-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_block_options_alter_block_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tx_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
